language: node_js

node_js:
  - 14.12.0

services:
  - docker

cache:
  directories:
    - node_modules

before_script:
  - docker-compose up -d mongo

script:
  - npm run coverage
  - cat coverage/lcov.info | coveralls
