language: node_js

node_js:
  - 12.14.0

cache:
  directories:
    - node_modules

env:
  - REQ_FILE = "./.env.test" MONGODB_VERSION=mongodb-linux-x86_64-4.0.14

install:
  - wget https://fastdl.mongodb.org/linux/${MONGODB_VERSION}.tgz
  - tar xzf ${MONGODB_VERSION}.tgz
  - ${MONGODB_VERSION}/bin/mongod --version
  - npm install

before_script:
  - mkdir ${MONGODB_VERSION}/data
  - ${MONGODB_VERSION}/bin/mongod --dbpath ${MONGODB_VERSION}/data --logpath ${MONGODB_VERSION}/mongodb.log --fork
