language: node_js

node_js:
  - 12.13.0

install:
  - wget https://fastdl.mongodb.org/linux/mongodb-linux-x86_64-4.0.10.tgz
  - tar xzf mongodb-linux-x86_64-4.0.10.tgz
  - ${PWD}/mongodb-linux-x86_64-4.0.10/bin/mongod --version
  - npm install

before_script:
  - mkdir ${PWD}/mongodb-linux-x86_64-4.0.10/data
  - ${PWD}/mongodb-linux-x86_64-4.0.10/bin/mongod --dbpath ${PWD}/mongodb-linux-x86_64-4.0.10/data --logpath ${PWD}/mongodb-linux-x86_64-4.0.10/mongodb.log --fork
