language: node_js

node_js:
  - 13.14.0

services:
  - docker

cache:
  directories:
    - node_modules

before_script:
  - docker run -d -p 27017:27017 mongo:4.2.3

script:
  - npm run coverage
  - cat coverage/lcov.info | coveralls
