language: node_js

node_js:
  - 12.14.0

services:
  - docker

cache:
  directories:
    - node_modules

env:
  - MONGODB_URI=mongodb://127.0.0.1:27017
    DATABASE_NAME=matcha-test

before_script:
  - docker run -d -p 27017:27017 mongo:4.2.3

script:
  - npm run coverage
  - cat coverage/lcov.info | coveralls
